### PR TITLE
Better way to handle gzip inflating

### PR DESCRIPTION
**Pull request by lalitkapoor**
replacing the way gzip content encoding is handled - using the compress library to inflate gzip encoded data instead of spawning a child process

### CODE REVIEW

**Comment by lalitkapoor** [comment]
See here for the pull request: https://github.com/pfleidi/node-wwwdude/pull/3

**Comment by pfleidi** [comment]
Thanks for your participation. The code looks fine and it doesn't break any unit tests. :)

**Comment by lalitkapoor** [comment]
awesome, glad I could help out :)

**Comment by lalitkapoor** [comment]
can you please update the version in package.json and publish to npmjs.org if it is in a stable enough state?

**Pull request merged**
